lint:
  multiqc_config:
    - report_comment
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Margherita Mutarelli, Lucio Di Filippo
  description: Analysis pipeline for SAMMY-seq
  force: false
  is_nfcore: true
  name: sammyseq
  org: nf-core
  outdir: .
  version: 1.0dev
